libtsd: dsp::filter::filter
filter()
template<typename T , typename Tc > Vector<T> dsp::filter::filter (const FRat< Tc > & h, const Vector< T > & x)
Filtering of a finite length signal by a filter defined by its transfert function
This function will only work for finite length signals. To filter streaming signals, better use one of the structure with context (see filter_fir(), filter_sois(), etc.).
Parameters
h Transfert function (can be IIR or FIR) or coefficients vector (can only be FIR).
x Input signal to be filtered
Returns
Output signal
For a FIR filter, this function computes the convolution product:
\[ y_n = (h \star x)_n = \sum_{k=0}^{K-1} h_k\cdot x_{n-k} \]
There will be as many output samples as input ones, by inserting virtual zeros before the beginning of the signal.
See also
filtfilt()
Referenced by dsp::telecom::waveform_ask(), dsp::telecom::waveform_fsk(), dsp::telecom::waveform_qam(), dsp::telecom::waveform_qpsk(), and dsp::telecom::waveform_π4_qpsk().